sonar.organization=vannadii
sonar.projectKey=vannadii_devplat
sonar.sources=packages
sonar.tests=packages
sonar.test.inclusions=packages/*/src/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=packages/*/dist/**,coverage/**,.devplat/**,packages/*/schemas/*.schema.json
