{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devplat.serviceAccountName" . }}
  labels:
    {{- include "devplat.labels" . | nindent 4 }}
{{- end }}
